import type { Counter, ServiceTypeDefinition, Token } from '../types/queue';

export const SERVICE_TYPES: ServiceTypeDefinition[] = [
  {
    id: 'account_services',
    name: 'Account & Verification',
    code: 'ACC',
    description: 'New account setup, KYC, compliance and profile changes',
    prefix: 'A',
    avgDurationMins: 8,
    iconName: 'UserCheck',
    badgeColor: 'bg-blue-500/15 text-blue-400 border-blue-500/30',
  },
  {
    id: 'cashier_billing',
    name: 'Cashier & Billing',
    code: 'CSH',
    description: 'Deposits, withdrawals, invoice settlements & fee payments',
    prefix: 'B',
    avgDurationMins: 4,
    iconName: 'CreditCard',
    badgeColor: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30',
  },
  {
    id: 'vip_services',
    name: 'VIP & Wealth Desk',
    code: 'VIP',
    description: 'Dedicated priority relationship management and advisory',
    prefix: 'V',
    avgDurationMins: 15,
    iconName: 'Crown',
    badgeColor: 'bg-amber-500/15 text-amber-400 border-amber-500/30',
  },
  {
    id: 'tech_support',
    name: 'Technical Support',
    code: 'TEC',
    description: 'Hardware authentication, mobile app troubleshooting & setup',
    prefix: 'T',
    avgDurationMins: 12,
    iconName: 'Cpu',
    badgeColor: 'bg-purple-500/15 text-purple-400 border-purple-500/30',
  },
  {
    id: 'express_drop',
    name: 'Express Document Drop',
    code: 'EXP',
    description: 'Quick paper submissions, stamp approvals and pickup',
    prefix: 'E',
    avgDurationMins: 3,
    iconName: 'Zap',
    badgeColor: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/30',
  },
];

export const INITIAL_COUNTERS: Counter[] = [
  {
    id: 'counter-1',
    name: 'Counter 1',
    code: 'C-01',
    staffName: 'Sarah Jenkins',
    supportedServiceIds: ['account_services', 'express_drop'],
    status: 'active',
    currentServingTokenId: 't-101',
    servedCountToday: 18,
    averageServiceMinutes: 7.5,
  },
  {
    id: 'counter-2',
    name: 'Counter 2',
    code: 'C-02',
    staffName: 'Michael Chang',
    supportedServiceIds: ['cashier_billing', 'express_drop'],
    status: 'active',
    currentServingTokenId: 't-102',
    servedCountToday: 26,
    averageServiceMinutes: 4.2,
  },
  {
    id: 'counter-3',
    name: 'Counter 3 (Priority)',
    code: 'C-03',
    staffName: 'Elena Rostova',
    supportedServiceIds: ['vip_services', 'account_services', 'cashier_billing', 'tech_support', 'express_drop'],
    status: 'active',
    currentServingTokenId: 't-103',
    servedCountToday: 12,
    averageServiceMinutes: 14.0,
  },
  {
    id: 'counter-4',
    name: 'Counter 4',
    code: 'C-04',
    staffName: 'David Miller',
    supportedServiceIds: ['tech_support'],
    status: 'active',
    currentServingTokenId: undefined,
    servedCountToday: 15,
    averageServiceMinutes: 11.5,
  },
];

const now = Date.now();
const min = 60 * 1000;

export const INITIAL_TOKENS: Token[] = [
  // Serving Tokens
  {
    id: 't-101',
    tokenNumber: 'A-101',
    customerName: 'Marcus Vance',
    contact: '+1 (555) 234-8901',
    serviceId: 'account_services',
    serviceName: 'Account & Verification',
    priority: 'regular',
    status: 'in_service',
    counterId: 'counter-1',
    counterName: 'Counter 1',
    staffName: 'Sarah Jenkins',
    createdAt: now - 22 * min,
    calledAt: now - 8 * min,
    serviceStartedAt: now - 7 * min,
    estimatedWaitMins: 0,
    notes: 'KYC Address re-verification',
  },
  {
    id: 't-102',
    tokenNumber: 'B-102',
    customerName: 'Amina Al-Mansoor',
    contact: '+1 (555) 456-1122',
    serviceId: 'cashier_billing',
    serviceName: 'Cashier & Billing',
    priority: 'regular',
    status: 'in_service',
    counterId: 'counter-2',
    counterName: 'Counter 2',
    staffName: 'Michael Chang',
    createdAt: now - 15 * min,
    calledAt: now - 3 * min,
    serviceStartedAt: now - 2 * min,
    estimatedWaitMins: 0,
  },
  {
    id: 't-103',
    tokenNumber: 'V-103',
    customerName: 'Arthur Pendelton',
    contact: '+1 (555) 789-3344',
    serviceId: 'vip_services',
    serviceName: 'VIP & Wealth Desk',
    priority: 'vip',
    status: 'in_service',
    counterId: 'counter-3',
    counterName: 'Counter 3 (Priority)',
    staffName: 'Elena Rostova',
    createdAt: now - 18 * min,
    calledAt: now - 5 * min,
    serviceStartedAt: now - 4 * min,
    estimatedWaitMins: 0,
    notes: 'Portfolio review',
  },

  // Waiting Tokens
  {
    id: 't-104',
    tokenNumber: 'A-104',
    customerName: 'Eleanor Roosevelt',
    contact: '+1 (555) 901-4455',
    serviceId: 'account_services',
    serviceName: 'Account & Verification',
    priority: 'senior_disabled',
    status: 'waiting',
    createdAt: now - 12 * min,
    estimatedWaitMins: 4,
    notes: 'Assistance requested with digital signature',
  },
  {
    id: 't-105',
    tokenNumber: 'T-105',
    customerName: 'Carlos Rodriguez',
    contact: '+1 (555) 321-9988',
    serviceId: 'tech_support',
    serviceName: 'Technical Support',
    priority: 'urgent',
    status: 'waiting',
    createdAt: now - 10 * min,
    estimatedWaitMins: 2,
    notes: 'Locked hardware security key',
  },
  {
    id: 't-106',
    tokenNumber: 'B-106',
    customerName: 'Sophia Lin',
    contact: '+1 (555) 654-7711',
    serviceId: 'cashier_billing',
    serviceName: 'Cashier & Billing',
    priority: 'regular',
    status: 'waiting',
    createdAt: now - 8 * min,
    estimatedWaitMins: 6,
  },
  {
    id: 't-107',
    tokenNumber: 'V-107',
    customerName: 'Garrison Sterling',
    contact: '+1 (555) 887-2200',
    serviceId: 'vip_services',
    serviceName: 'VIP & Wealth Desk',
    priority: 'vip',
    status: 'waiting',
    createdAt: now - 6 * min,
    estimatedWaitMins: 10,
  },
  {
    id: 't-108',
    tokenNumber: 'E-108',
    customerName: 'Liam O’Connor',
    contact: '+1 (555) 432-8877',
    serviceId: 'express_drop',
    serviceName: 'Express Document Drop',
    priority: 'regular',
    status: 'waiting',
    createdAt: now - 3 * min,
    estimatedWaitMins: 8,
  },
  {
    id: 't-109',
    tokenNumber: 'A-109',
    customerName: 'Kavita Patel',
    contact: '+1 (555) 555-1234',
    serviceId: 'account_services',
    serviceName: 'Account & Verification',
    priority: 'regular',
    status: 'waiting',
    createdAt: now - 1 * min,
    estimatedWaitMins: 14,
  },

  // Completed Today
  {
    id: 't-098',
    tokenNumber: 'B-098',
    customerName: 'Hannah Abbott',
    contact: '+1 (555) 111-2233',
    serviceId: 'cashier_billing',
    serviceName: 'Cashier & Billing',
    priority: 'regular',
    status: 'completed',
    counterId: 'counter-2',
    counterName: 'Counter 2',
    staffName: 'Michael Chang',
    createdAt: now - 50 * min,
    calledAt: now - 35 * min,
    serviceStartedAt: now - 34 * min,
    completedAt: now - 30 * min,
    estimatedWaitMins: 0,
  },
  {
    id: 't-099',
    tokenNumber: 'A-099',
    customerName: 'Devon Miles',
    contact: '+1 (555) 999-8877',
    serviceId: 'account_services',
    serviceName: 'Account & Verification',
    priority: 'regular',
    status: 'completed',
    counterId: 'counter-1',
    counterName: 'Counter 1',
    staffName: 'Sarah Jenkins',
    createdAt: now - 45 * min,
    calledAt: now - 28 * min,
    serviceStartedAt: now - 27 * min,
    completedAt: now - 20 * min,
    estimatedWaitMins: 0,
  },
];
